# fly.toml - Configuração completa para Laravel no Fly.io
app = "myapp-lajpsg"

# Build usando Dockerfile na raiz do projeto
[build]
  dockerfile = "Dockerfile"

# Configuração de serviços e portas
[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.tcp_checks]]
    interval = 10000
    timeout = 2000
    restart_limit = 0

# Volumes persistentes para Laravel
[mounts]
  source = "laravel-storage"
  destination = "/app/storage"

  source = "laravel-cache"
  destination = "/app/bootstrap/cache"

# Configuração experimental
[experimental]
  auto_rollback = true

# Comandos pós-deploy
[deploy]
  release_command = """
    php artisan migrate &&
    php artisan config:cache &&
    php artisan route:cache &&
    php artisan view:cache
  """
